### PR TITLE
GCI-82: Add language support and improve label text

### PR DESCRIPTION
**Pull request by vincentes**
Adding language support improves the UI for users from different countries. In this commit language support is implemented with the spanish language included. Also, some label texts have been simplified and made easier to understand. There's a problem here though. The popup translations don't appear to be working. For example, `dataimporttool.fileLocationPopup` shows as "dataimporttool.fileLocationPopup" when it should show the translation for it. This only happens in the english translation, the spanish version works fine. I'm not sure about the reason of this behaviour but I don't think the implemention and translations are a problem.

### CODE REVIEW

**Comment by ch3ck** [comment]
@Vincentes, I don't see a task instance for this on the GCI dashboard. Is this an independent contribution to the module or a GCI task? If I'm correct you cannot work on two tasks at once right?

**Comment by robbyoconnor** [comment]
Closing until he has an associated GCI task -- students are free to work on things **BUT** must have a task associated before a PR is made. Pushing to your Github branch is okay, making a PR is not. 

I checked with Stephanie and other mentors and it seemed to be consensus -- this is the only fair and sane way.

**Comment by vincentes** [comment]
Well.. Looks like another student has implemented language support. I'll refactor this PR to include the spanish translations.

**Comment by robbyoconnor** [comment]
You're gonna have to rebase ;)

**Comment by vincentes** [comment]
Closing this. I'm going to make another PR as the title isn't relevant anymore and leave this as reference to #8.

**Pull request closed without merging**
