### PR TITLE
GCI-82: Fix #8 and add es, pt, it translations

### PR DESCRIPTION
**Pull request by vincentes**
The original pull request was #7 but while it was in stand-by, another student made pull request #8 with the content from #7. You can tell it is derived from #7 because the title specifically says "Moved freetext to message.properties" though #7 message labels and logic are there when that was not the intention. The derivation made some items not work properly, this issue was addressed in this new pull request. For example, the file name label was not working because the form element was closed too soon which caused it to be indented. And also, I changed the message names to the original #7 names. While this is opensource and no one's code belongs to anyone, we are participating in GCI which means everything should be original. And please, if there is already a pull request focused in fixing or adding something, do NOT make another with the same objective and content. Anyways, on topic: I added translations for spanish and overrided #8 commits to match #7 while keeping #8's actual additions (comments, spacing). More translations for spanish are planned to be added soon.

A screenshot showing the spanish translations can be found here: http://i.imgur.com/IUTQyHz.png

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Screenshots ;)

**Comment by ch3ck** [comment]
@Vincentes Well this is something serious you're talking of here. Accusing another student of copying your work is pretty serious. First of all you made a pull request for a task which you did not claim which is _WRONG!_. Secondly Our aim of this task is to improve the migration settings page is mainly focused on the UI? I think the other student you're referring to here is @collinsnji  which I think he asked for permission to move freetext to the messages.properties file given the fact that the UI had already been improved by @Breta01; which I granted. I think it was pretty clear anyone could move freetext to messages.properties. It's clearly stated in previous GCI tasks if I'm not mistaken. Besides I think you should have discussed with me on the required changes to be made to the migration settings page.

When it comes to translation, I would have preferred a portuguese translation since the Data Import Tool is predominantly used in Mozambique and Southern Africa.

@robbyoconnor  Do you have anything to say here?

**Comment by robbyoconnor** [comment]
@Ch3ck, in his defense, it was partially on us. He had a Windows Phone App task sit for days. While it's not great, we can't expect students to sit on their hands. This was a case where things were a bit too close https://github.com/openmrs/openmrs-module-dataimporttool/pull/8 is a little bit too close to #7 for my tastes personally...even if he made it in the wrong order (which is fine, it's their gamble) but the fact remains we should figure out if it was copied or not. These things start to repeat themselves after awhile so I don't know.

**Comment by ch3ck** [comment]
Yes @robbyoconnor , Looking at the two PRs they are very close. Just slight changes in variable names. Given the fact that @Vincentes made his first, I'll get on to @collinsnji  with this. In the mean time @Vincentes  I prefer the #8 convention to the variable names since they respect [this](https://github.com/openmrs/openmrs-module-dataimporttool/blob/master/api/src/main/java/org/openmrs/module/dataimporttool/DataImportTool.java)

I think it will be better for you rename your variables to respect these. Let me add my comments on the commit

**Comment by collinsnji** [comment]
Hi @Ch3ck @robbyoconnor I have not copied @Vincentes work. This task similar to a lot of my previous work. I did [mine](https://github.com/openmrs/openmrs-module-dataimporttool/pull/8) from scratch.

**Comment by vincentes** [comment]
I'm sorry, It's wrong to accuse but that's not main problem here. Why should someone make a pull request of the same objective and content as another pull request? Everything was being done in #7 and there was no reason to make another pull request. 

The reason why I accused @collinsnji is because the changes made to the labels are the same as #7, when clearly that's not #8's intention.
About the naming convention, what if you want to use for example "File name" in another page? `matchFileName` would be misleading. The change made to dbName are because in my opinion, message naming should be as most descriptive as it can be. This label naming benefits message recycling.

I live next to a portuguese speaking country, I'd love to learn portuguese but currently I don't know the language. I'm sorry but spanish is the [third most spoken language in the world](https://en.wikipedia.org/wiki/Spanish_language#Estimated_number_of_speakers). And also, as shown in the image, the changes in this pull request were asked in the Telegram chat and got no response from @Ch3ck.

a081

And @collinsnji . Your similar tasks were done in sequence of this task. Please clarify why my exact messages are in your pull request. I generalized the messages by changing `Matching File Name` to `File name` for example, and those changes are in #8. And also, besides the labels, the same logic used in #7 is in your pull request with some spaces removed.
from this

``` html
<div id="button">
<td colspan="2"><input type="submit" value="${startMigration}"></td>
</div>
```

to the following

``` html
<div id="button"><td colspan="2"><input type="submit" value="${startMigration}"></td></div>
```

The point is: Was it really necessary to make another pull request?

**Comment by ch3ck** [comment]
Alright @Vincentes Let's not make this competition more tiring than it already is. Just make the necessary changes I've made to you patch and submit. I'll merge. Sorry for all the mix with these issues since there was a delay in reviewing your App. Any ways. I will advise to comment on the GCI task instance for any clarifications since I"m not always on Telegram. Hence forth If there are any changes to the DIT you could improve on the help.jsp by making it user friendly anything else you think can be done. Good work guys I'm impressed @Vincentes @collinsnji Keep up!

**Comment by vincentes** [comment]
Alright, thanks @Ch3ck! I'll apply the necessary changes.

**Comment by ch3ck** [comment]
No problem, It'll be great for you guys to keep up a collaborative spirit both in this GCI contest and beyond. The world of Software Development is very large and long. Good work to you both! (y)

**Comment by vincentes** [comment]
Applied the changes. Fixed config.xml typo and updated variable naming. :)

**Comment by vincentes** [comment]
1abc
2abv

**Comment by vincentes** [comment]
@Ch3ck I followed your recommendation. I added translations for portuguese.

**Comment by vincentes** [comment]
a081png

**Comment by robbyoconnor** [comment]
Make sure that these translate correctly...don't use Google
Translate...that is my concern :)

--Rob

**Comment by vincentes** [comment]
@robbyoconnor Part of my family live in Brazil. They helped me.

**Comment by vincentes** [comment]
Added Italian translations, no translator used.
a082

**Comment by ch3ck** [comment]
Wow this is good @Vincentes

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67olt-a7&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=LIhtep0O&invitationId=6130897022737276929








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67olt-a7&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHi0xcTQnWzrgAAAVRVSbli_PvIC1gC6e1Sb4PdsKn6tYlHBz4LhfYlWoTt8rfImMmx1U5oLWCNF_x7I9QwtZrruxaNz6JndoA9Urp4Tt_0Bdf-0q59dMxoQssyOA9KuPNs_fBVBQA6kjfnxZt1PUlOesh8s3U0sizmZMyZqQ554ZzG48PTqq41sVGWQxfVrEUI&eid=0-ini67olt-a7


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67olt-a7&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
