### PR TITLE
GCI-82: User Interface Data Import Tool, Moved free text to messages.properties

### PR DESCRIPTION
**Pull request by collinsnji**
*Moved free text to messages.properties

### CODE REVIEW

**Comment by ch3ck** [comment]
@collinsnji First and foremost, Squash your commits into one. I see the updates from the master branch has an empty commit.

Can you add some screenshots for this?

**Comment by collinsnji** [comment]
ok @Ch3ck I will submit them ASAP.

**Comment by ch3ck** [comment]
You should upload the images here(Not on the GCI dashboard) so we can work on them @collinsnji

**Comment by collinsnji** [comment]
screenshot from 2016-01-14 09-59-05
screenshot from 2016-01-14 10-00-44

@Ch3ck  Here are the screenshots. I have removed the empty commit. Can you please approve this?

**Comment by collinsnji** [comment]
Hi @Ch3ck  I made the mOptions fix.

**Comment by ch3ck** [comment]
Alright, Nice work @collinsnji . This patch is fine now.

**Comment by collinsnji** [comment]
:+1:

**Comment by vincentes** [comment]
This is exactly #7. The only difference is that the message.properties names are changed. The logic and labels are the same. Why make a PR with the same content as another?

**Pull request merged**
