### PR TITLE
Update help.jsp content and formatting

### PR DESCRIPTION
**Pull request by vincentes**
In this pull request the use of tags is updated.
For example, this:

``` html
<br> <i>Content</i>
<br> <i>More content</i>
```

is changed to this

``` html
<i>
<p>Content</p>
<p>More content</p>
</i>
```

This change makes it easier to read and it involves less typing.
Also, a lot of the `<br>` tags have been removed to reduce spacing. The broken links were fixed by using `href` and target `_blank`. Some more content was added to the page.

This page needs @Breta01 styling. :+1:

### CODE REVIEW

**Comment by Breta01** [comment]
@Ch3ck I can look on the styling of this page if you want :smiley:

**Comment by ch3ck** [comment]
By all means @Breta01 I think you should add the styling here

**Comment by ch3ck** [comment]
@Vincentes You should fix this commit, I see some work here from @collinsnji  which has already been merged. Add some screenshots for this

**Comment by vincentes** [comment]
Working on that.

**Comment by vincentes** [comment]
a083

**Comment by ch3ck** [comment]
Nice work @Vincentes

**Comment by vincentes** [comment]
@Ch3ck Thank you. :smile: 
Should we do this with the README.md file too? Also, the title counting typo is fixed. The screenshot is outdated. :stuck_out_tongue:

**Pull request merged**
