### PR TITLE
Revamped status.jsp and error.jsp pages

### PR DESCRIPTION
**Pull request by ddworken**
I threw the plain html up on my server so you can see what they look like: 
1. [error.jsp](http://daviddworken.com/openmrs/error.html)
2. [status.jsp](http://daviddworken.com/openmrs/status.html)

I made sure to follow the OpenMRS styleguide and am using Open Sans as the font.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Add a screenshot proving you ran this to test it.

**Comment by robbyoconnor** [comment]
Also dude, learn how to use branches!!

**Comment by robbyoconnor** [comment]
@Ch3ck this is you man!

**Comment by ch3ck** [comment]
Alright, @robbyoconnor  Will look into this. Could you please add some screenshots on the changes you've made. I'll try to test and see

**Comment by ch3ck** [comment]
@ddworken  Could you move the CSS styles to a separate file? Adding the CSS styles into the same file just clutters the code. see this: https://github.com/openmrs/openmrs-module-dataimporttool/commit/d0ec29838e3357f5696c738ca84bec3cbb475f7f

**Comment by ch3ck** [comment]
@ddworken  You took alot of time to submit the screenshots for this. I will have advise you revise this commit in relation to the most recent changes and see any fixes you can make. I will merge the code provided you've added some screenshots and some fixes.

**Comment by vincentes** [comment]
What's the bug here exactly? href?

**Comment by ddworken** [comment]
@Vincentes I went away without internet connection for a week and the deadline lapsed. I closed the PR since #5 was already accepted. You can go ahead and ignore this PR.

**Comment by vincentes** [comment]
Ah, sounds bad. You can always reclaim the task and do other changes. :smile:

**Pull request closed without merging**
